site_name: CLAM
site_url: https://clam-community.github.io/
repo_url: https://github.com/CLAM-community/CLAM-community.github.io
edit_uri: edit/main/docs/
theme:
    name: material
    logo: assets/branding/svg/clam-logo-white-buffer-no-margin.svg
    favicon: assets/branding/png/clam-logo-white-buffer.png
    features:
        - content.action.edit
    palette:
        primary: blue
        accent: blue

extra:
    zulip_url: https://clam-community.zulipchat.com/

markdown_extensions:
    - admonition
    - md_in_html
    - attr_list
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
    - index.md
    - calendar.md
    - code-of-conduct.md
plugins:
    - macros
    - mkdocs-jupyter:
          ignore_h1_titles: True
