name: CI
on:
    push:
        branches:
            - "main"
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
              with:
                persist-credentials: false
            - uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
              with:
                  pixi-version: latest
            - run: pixi run mkdocs build
            - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
              with:
                  name: Website
                  path: ./site
                  if-no-files-found: error
                  retention-days: 3
    zizmor:
        name: GHA Security Analysis using Zizmor
        runs-on: ubuntu-latest
        permissions:
            security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Run zizmor
              uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
