name: Deploy GitHub Pages

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
              with:
                  persist-credentials: false
            - name: Configure Git Credentials
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            - uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
              with:
                  pixi-version: latest
            - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
            - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
              with:
                  key: mkdocs-material-${{ env.cache_id }}
                  path: .cache
                  restore-keys: |
                      mkdocs-material-
            - run: pixi run mkdocs gh-deploy --force
